.TH pressor 1 "January 2023" "1.0" "Pressor Manual"
.SH NAME
Pressor \- The all-in-one tool for media compression
.SH NOTE
This man page is a test. The documentation will be written once the first version of the program is released
.SH DESCRIPTION
Pressor is a command line tool for compressing media files, including photos, videos, and audio. It provides a variety of options for compressing files, including codecs, quality, and compression efficiency.
.SH SYNOPSIS
.B pressor
[OPTIONS]
.SH OPTIONS
.TP
.B -i
Input file or directory.
