#!/bin/bash

readarray -t files <<< $(find . -type f)
readarray -t dates <<< $(find . -type f -printf '%CY%Cm%Cd_%CH%CM%CS\n' -type f | sed -E 's:.{11}$::g')
readarray -t statDates <<< $(find . -type f -printf '%CY%Cm%Cd%CH%CM.%CS\n' -type f | sed -E 's:.{11}$::g')
index=0

for i in "${files[@]}"; do
  extention="${i##*.}"
  extention="${extention@L}"
  if [[ "$extention" =~ '.'|'/'|[0-9][0-9] ]]; then echo "INVALID FILE ($i)"; exit; fi
  if [[ ! "$extention" =~ [a-z]{1}[a-z0-9]{2,3} ]]; then echo "INVALID FILE ($i)"; exit; fi
  if [[ "$extention" == 'jpeg' ]]; then extention='jpg'; fi
  if [[ "$i" =~ '20'[1-2][0-9][-|\.|_]*[0-1][0-9][-|\.|_]*[0-3][0-9][-|\.|_]{0,1}[0-9]{0,2}[-|\.|_]{0,1}[0-9]{0,2}[-|\.|_]{0,1}[0-9]{0,2} ]]; then
    date="${BASH_REMATCH//[^0-9]/}"
    if [[ "${#date}" == 14 ]]; then
      date="${date:0:8}_${date:8}"
      statDate="${date:0:8}${date:9:4}.${date:13:2}"
      echo -ne "\e[32m"
    else
      date="${date:0:8}_000000"
      statDate="${date:0:8}0000.00"
      echo -ne "\e[33m"
    fi
    changeDate='true'
  else
    date="${dates[index]}"
    statDate="${statDates[index]}"
    echo -ne "\e[31m"
    changeDate='false'
  fi
  increment=1
  while [[ "$log" =~ "$date" ]]; do
    date="${date:0:15}_$increment"
    ((increment++))
  done
  echo -e "$statDate > $date.$extention\e[35m > \e[0m$i"
  if [[ "$changeDate" == true ]]; then
    touch "$i" -t "$statDate"
  fi
  mv "$i" "$date.$extention"
  log+="$date\n"
  ((index++))
done

#echo -e "${log::-2}" > log
